### ISSUE TITLE
HTML SUCKS

### ISSUE THREAD

**Issue by anshumancodes** [ushiecodes/School-Project#1]
STOP UPLOADING SHCOOL PROJECTS IN GITHUB

**Comment by ushiecodes** [comment]
Thankyou for your suggestion dear anshuman, to my best knowledge inorder to do something you got to start somewhere. Uploading my school project is far better than uploading nothing, thats how improvement works, progressively and gradually. You don't wake up a coder and upload state-of-the-art projects with the latest framework as far as HTML goes. Your career is alive because of HTML, afterall that is the backbone of web development. My advice for you is stop being unprofessional and start doing your lab assignments you have been avoiding since last 2 semesters. Thankyou for reading <3

**Comment by anshumancodes** [comment]
too much yapping coming from someone whose entire repo is html
